# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

test:
  stage: test
  script:
    - yarn install
    - yarn test
